version: '3'
services:
  app:
    build: .
    restart: always
    read_only: true
    ports:
     - "5111:5000"
    env_file:
     - ./.env
    volumes:
     - ./tasks:/tasks
    stop_signal: SIGINT
    privileged: true
  db:
    image: postgres
    restart: always
    env_file:
     - ./.env
    volumes:
      - golf_pgdata:/var/lib/postgresql/data

volumes:
    golf_pgdata:
