version: '3'
services:
  app:
    build: .
    restart: always
    read_only: true
    ports:
     - "5111:5000"
    environment:
     - FLASK_APP=app.py
     - FLASK_DB=postgresql://golf:socek@db/golf
    stop_signal: SIGINT
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=socek
      - POSTGRES_USER=golf
      - POSTGRES_DB=golf
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
